#include "RHID3D12.h"

struct DxgiFormatMapping
{
	ERHIFormat	RHIFormat;
	DXGI_FORMAT DxgiFormat;
};

static constexpr std::array<DxgiFormatMapping, static_cast<size_t>(ERHIFormat::COUNT)> FORMAT_TABLE = { {
	{ ERHIFormat::UNKNOWN, DXGI_FORMAT_UNKNOWN },
	{ ERHIFormat::R8_UINT, DXGI_FORMAT_R8_TYPELESS },
	{ ERHIFormat::R8_SINT, DXGI_FORMAT_R8_TYPELESS },
	{ ERHIFormat::R8_UNORM, DXGI_FORMAT_R8_TYPELESS },
	{ ERHIFormat::R8_SNORM, DXGI_FORMAT_R8_TYPELESS },
	{ ERHIFormat::RG8_UINT, DXGI_FORMAT_R8G8_TYPELESS },
	{ ERHIFormat::RG8_SINT, DXGI_FORMAT_R8G8_TYPELESS },
	{ ERHIFormat::RG8_UNORM, DXGI_FORMAT_R8G8_TYPELESS },
	{ ERHIFormat::RG8_SNORM, DXGI_FORMAT_R8G8_TYPELESS },
	{ ERHIFormat::R16_UINT, DXGI_FORMAT_R16_TYPELESS },
	{ ERHIFormat::R16_SINT, DXGI_FORMAT_R16_TYPELESS },
	{ ERHIFormat::R16_UNORM, DXGI_FORMAT_R16_TYPELESS },
	{ ERHIFormat::R16_SNORM, DXGI_FORMAT_R16_TYPELESS },
	{ ERHIFormat::R16_FLOAT, DXGI_FORMAT_R16_TYPELESS },
	{ ERHIFormat::BGRA4_UNORM, DXGI_FORMAT_B4G4R4A4_UNORM },
	{ ERHIFormat::B5G6R5_UNORM, DXGI_FORMAT_B5G6R5_UNORM },
	{ ERHIFormat::B5G5R5A1_UNORM, DXGI_FORMAT_B5G5R5A1_UNORM },
	{ ERHIFormat::RGBA8_UINT, DXGI_FORMAT_R8G8B8A8_TYPELESS },
	{ ERHIFormat::RGBA8_SINT, DXGI_FORMAT_R8G8B8A8_TYPELESS },
	{ ERHIFormat::RGBA8_UNORM, DXGI_FORMAT_R8G8B8A8_TYPELESS },
	{ ERHIFormat::RGBA8_SNORM, DXGI_FORMAT_R8G8B8A8_TYPELESS },
	{ ERHIFormat::BGRA8_UNORM, DXGI_FORMAT_B8G8R8A8_TYPELESS },
	{ ERHIFormat::SRGBA8_UNORM, DXGI_FORMAT_R8G8B8A8_TYPELESS },
	{ ERHIFormat::SBGRA8_UNORM, DXGI_FORMAT_B8G8R8A8_TYPELESS },
	{ ERHIFormat::R10G10B10A2_UNORM, DXGI_FORMAT_R10G10B10A2_TYPELESS },
	{ ERHIFormat::R11G11B10_FLOAT, DXGI_FORMAT_R11G11B10_FLOAT },
	{ ERHIFormat::RG16_UINT, DXGI_FORMAT_R16G16_TYPELESS },
	{ ERHIFormat::RG16_SINT, DXGI_FORMAT_R16G16_TYPELESS },
	{ ERHIFormat::RG16_UNORM, DXGI_FORMAT_R16G16_TYPELESS },
	{ ERHIFormat::RG16_SNORM, DXGI_FORMAT_R16G16_TYPELESS },
	{ ERHIFormat::RG16_FLOAT, DXGI_FORMAT_R16G16_TYPELESS },
	{ ERHIFormat::R32_UINT, DXGI_FORMAT_R32_TYPELESS },
	{ ERHIFormat::R32_SINT, DXGI_FORMAT_R32_TYPELESS },
	{ ERHIFormat::R32_FLOAT, DXGI_FORMAT_R32_TYPELESS },
	{ ERHIFormat::RGBA16_UINT, DXGI_FORMAT_R16G16B16A16_TYPELESS },
	{ ERHIFormat::RGBA16_SINT, DXGI_FORMAT_R16G16B16A16_TYPELESS },
	{ ERHIFormat::RGBA16_FLOAT, DXGI_FORMAT_R16G16B16A16_TYPELESS },
	{ ERHIFormat::RGBA16_UNORM, DXGI_FORMAT_R16G16B16A16_TYPELESS },
	{ ERHIFormat::RGBA16_SNORM, DXGI_FORMAT_R16G16B16A16_TYPELESS },
	{ ERHIFormat::RG32_UINT, DXGI_FORMAT_R32G32_TYPELESS },
	{ ERHIFormat::RG32_SINT, DXGI_FORMAT_R32G32_TYPELESS },
	{ ERHIFormat::RG32_FLOAT, DXGI_FORMAT_R32G32_TYPELESS },
	{ ERHIFormat::RGB32_UINT, DXGI_FORMAT_R32G32B32_TYPELESS },
	{ ERHIFormat::RGB32_SINT, DXGI_FORMAT_R32G32B32_TYPELESS },
	{ ERHIFormat::RGB32_FLOAT, DXGI_FORMAT_R32G32B32_TYPELESS },
	{ ERHIFormat::RGBA32_UINT, DXGI_FORMAT_R32G32B32A32_TYPELESS },
	{ ERHIFormat::RGBA32_SINT, DXGI_FORMAT_R32G32B32A32_TYPELESS },
	{ ERHIFormat::RGBA32_FLOAT, DXGI_FORMAT_R32G32B32A32_TYPELESS },

	{ ERHIFormat::D16, DXGI_FORMAT_R16_TYPELESS },
	{ ERHIFormat::D24S8, DXGI_FORMAT_R24G8_TYPELESS },
	{ ERHIFormat::X24G8_UINT, DXGI_FORMAT_R24G8_TYPELESS },
	{ ERHIFormat::D32, DXGI_FORMAT_R32_TYPELESS },
	{ ERHIFormat::D32S8, DXGI_FORMAT_R32G8X24_TYPELESS },
	{ ERHIFormat::X32G8_UINT, DXGI_FORMAT_R32G8X24_TYPELESS },

	{ ERHIFormat::BC1_UNORM, DXGI_FORMAT_BC1_TYPELESS },
	{ ERHIFormat::BC1_UNORM_SRGB, DXGI_FORMAT_BC1_TYPELESS },
	{ ERHIFormat::BC2_UNORM, DXGI_FORMAT_BC2_TYPELESS },
	{ ERHIFormat::BC2_UNORM_SRGB, DXGI_FORMAT_BC2_TYPELESS },
	{ ERHIFormat::BC3_UNORM, DXGI_FORMAT_BC3_TYPELESS },
	{ ERHIFormat::BC3_UNORM_SRGB, DXGI_FORMAT_BC3_TYPELESS },
	{ ERHIFormat::BC4_UNORM, DXGI_FORMAT_BC4_TYPELESS },
	{ ERHIFormat::BC4_SNORM, DXGI_FORMAT_BC4_TYPELESS },
	{ ERHIFormat::BC5_UNORM, DXGI_FORMAT_BC5_TYPELESS },
	{ ERHIFormat::BC5_SNORM, DXGI_FORMAT_BC5_TYPELESS },
	{ ERHIFormat::BC6H_UFLOAT, DXGI_FORMAT_BC6H_TYPELESS },
	{ ERHIFormat::BC6H_SFLOAT, DXGI_FORMAT_BC6H_TYPELESS },
	{ ERHIFormat::BC7_UNORM, DXGI_FORMAT_BC7_TYPELESS },
	{ ERHIFormat::BC7_UNORM_SRGB, DXGI_FORMAT_BC7_TYPELESS },
} };

DXGI_FORMAT ToDxgiFormat(ERHIFormat RHIFormat)
{
	assert(RHIFormat < ERHIFormat::COUNT);
	assert(FORMAT_TABLE[uint32_t(RHIFormat)].RHIFormat == RHIFormat);
	return FORMAT_TABLE[uint32_t(RHIFormat)].DxgiFormat;
}
