#include "RHIVulkan.h"

struct VulkanFormatMapping
{
	ERHIFormat RHIFormat;
	VkFormat   VulkanFormat;
};

static constexpr std::array<VulkanFormatMapping, static_cast<size_t>(ERHIFormat::COUNT)> FORMAT_TABLE = { {
	{ ERHIFormat::UNKNOWN, VK_FORMAT_UNDEFINED },
	{ ERHIFormat::R8_UINT, VK_FORMAT_R8_UINT },
	{ ERHIFormat::R8_SINT, VK_FORMAT_R8_SINT },
	{ ERHIFormat::R8_UNORM, VK_FORMAT_R8_UNORM },
	{ ERHIFormat::R8_SNORM, VK_FORMAT_R8_SNORM },
	{ ERHIFormat::RG8_UINT, VK_FORMAT_R8G8_UINT },
	{ ERHIFormat::RG8_SINT, VK_FORMAT_R8G8_SINT },
	{ ERHIFormat::RG8_UNORM, VK_FORMAT_R8G8_UNORM },
	{ ERHIFormat::RG8_SNORM, VK_FORMAT_R8G8_SNORM },
	{ ERHIFormat::R16_UINT, VK_FORMAT_R16_UINT },
	{ ERHIFormat::R16_SINT, VK_FORMAT_R16_SINT },
	{ ERHIFormat::R16_UNORM, VK_FORMAT_R16_UNORM },
	{ ERHIFormat::R16_SNORM, VK_FORMAT_R16_SNORM },
	{ ERHIFormat::R16_FLOAT, VK_FORMAT_R16_SFLOAT },
	{ ERHIFormat::BGRA4_UNORM, VK_FORMAT_B4G4R4A4_UNORM_PACK16 },
	{ ERHIFormat::B5G6R5_UNORM, VK_FORMAT_B5G6R5_UNORM_PACK16 },
	{ ERHIFormat::B5G5R5A1_UNORM, VK_FORMAT_B5G5R5A1_UNORM_PACK16 },
	{ ERHIFormat::RGBA8_UINT, VK_FORMAT_R8G8B8A8_UINT },
	{ ERHIFormat::RGBA8_SINT, VK_FORMAT_R8G8B8A8_SINT },
	{ ERHIFormat::RGBA8_UNORM, VK_FORMAT_R8G8B8A8_UNORM },
	{ ERHIFormat::RGBA8_SNORM, VK_FORMAT_R8G8B8A8_SNORM },
	{ ERHIFormat::BGRA8_UNORM, VK_FORMAT_B8G8R8A8_UNORM },
	{ ERHIFormat::SRGBA8_UNORM, VK_FORMAT_R8G8B8A8_SRGB },
	{ ERHIFormat::SBGRA8_UNORM, VK_FORMAT_B8G8R8A8_SRGB },
	{ ERHIFormat::R10G10B10A2_UNORM, VK_FORMAT_A2B10G10R10_UNORM_PACK32 },
	{ ERHIFormat::R11G11B10_FLOAT, VK_FORMAT_B10G11R11_UFLOAT_PACK32 },
	{ ERHIFormat::RG16_UINT, VK_FORMAT_R16G16_UINT },
	{ ERHIFormat::RG16_SINT, VK_FORMAT_R16G16_SINT },
	{ ERHIFormat::RG16_UNORM, VK_FORMAT_R16G16_UNORM },
	{ ERHIFormat::RG16_SNORM, VK_FORMAT_R16G16_SNORM },
	{ ERHIFormat::RG16_FLOAT, VK_FORMAT_R16G16_SFLOAT },
	{ ERHIFormat::R32_UINT, VK_FORMAT_R32_UINT },
	{ ERHIFormat::R32_SINT, VK_FORMAT_R32_SINT },
	{ ERHIFormat::R32_FLOAT, VK_FORMAT_R32_SFLOAT },
	{ ERHIFormat::RGBA16_UINT, VK_FORMAT_R16G16B16A16_UINT },
	{ ERHIFormat::RGBA16_SINT, VK_FORMAT_R16G16B16A16_SINT },
	{ ERHIFormat::RGBA16_FLOAT, VK_FORMAT_R16G16B16A16_SFLOAT },
	{ ERHIFormat::RGBA16_UNORM, VK_FORMAT_R16G16B16A16_UNORM },
	{ ERHIFormat::RGBA16_SNORM, VK_FORMAT_R16G16B16A16_SNORM },
	{ ERHIFormat::RG32_UINT, VK_FORMAT_R32G32_UINT },
	{ ERHIFormat::RG32_SINT, VK_FORMAT_R32G32_SINT },
	{ ERHIFormat::RG32_FLOAT, VK_FORMAT_R32G32_SFLOAT },
	{ ERHIFormat::RGB32_UINT, VK_FORMAT_R32G32B32_UINT },
	{ ERHIFormat::RGB32_SINT, VK_FORMAT_R32G32B32_SINT },
	{ ERHIFormat::RGB32_FLOAT, VK_FORMAT_R32G32B32_SFLOAT },
	{ ERHIFormat::RGBA32_UINT, VK_FORMAT_R32G32B32A32_UINT },
	{ ERHIFormat::RGBA32_SINT, VK_FORMAT_R32G32B32A32_SINT },
	{ ERHIFormat::RGBA32_FLOAT, VK_FORMAT_R32G32B32A32_SFLOAT },
	{ ERHIFormat::D16, VK_FORMAT_D16_UNORM },
	{ ERHIFormat::D24S8, VK_FORMAT_D24_UNORM_S8_UINT },
	{ ERHIFormat::X24G8_UINT, VK_FORMAT_D24_UNORM_S8_UINT },
	{ ERHIFormat::D32, VK_FORMAT_D32_SFLOAT },
	{ ERHIFormat::D32S8, VK_FORMAT_D32_SFLOAT_S8_UINT },
	{ ERHIFormat::X32G8_UINT, VK_FORMAT_D32_SFLOAT_S8_UINT },
	{ ERHIFormat::BC1_UNORM, VK_FORMAT_BC1_RGB_UNORM_BLOCK },
	{ ERHIFormat::BC1_UNORM_SRGB, VK_FORMAT_BC1_RGB_SRGB_BLOCK },
	{ ERHIFormat::BC2_UNORM, VK_FORMAT_BC2_UNORM_BLOCK },
	{ ERHIFormat::BC2_UNORM_SRGB, VK_FORMAT_BC2_SRGB_BLOCK },
	{ ERHIFormat::BC3_UNORM, VK_FORMAT_BC3_UNORM_BLOCK },
	{ ERHIFormat::BC3_UNORM_SRGB, VK_FORMAT_BC3_SRGB_BLOCK },
	{ ERHIFormat::BC4_UNORM, VK_FORMAT_BC4_UNORM_BLOCK },
	{ ERHIFormat::BC4_SNORM, VK_FORMAT_BC4_SNORM_BLOCK },
	{ ERHIFormat::BC5_UNORM, VK_FORMAT_BC5_UNORM_BLOCK },
	{ ERHIFormat::BC5_SNORM, VK_FORMAT_BC5_SNORM_BLOCK },
	{ ERHIFormat::BC6H_UFLOAT, VK_FORMAT_BC6H_UFLOAT_BLOCK },
	{ ERHIFormat::BC6H_SFLOAT, VK_FORMAT_BC6H_SFLOAT_BLOCK },
	{ ERHIFormat::BC7_UNORM, VK_FORMAT_BC7_UNORM_BLOCK },
	{ ERHIFormat::BC7_UNORM_SRGB, VK_FORMAT_BC7_SRGB_BLOCK },
} };

VkFormat ToVkFormat(ERHIFormat RHIFormat)
{
	assert(RHIFormat < ERHIFormat::COUNT);
	assert(FORMAT_TABLE[uint32_t(RHIFormat)].RHIFormat == RHIFormat);
	return FORMAT_TABLE[uint32_t(RHIFormat)].VulkanFormat;
}
